# Generated by Django 4.0.2 on 2022-05-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='video_url',
            new_name='book_url',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url_lit',
            field=models.CharField(max_length=100, verbose_name='Ссылка на литрес'),
        ),
    ]
