# Generated by Django 4.0.2 on 2022-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_video_url_book_book_url_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.FileField(null=True, upload_to='books/', verbose_name='Ссылка на файл'),
        ),
    ]
