# Generated by Django 4.0.2 on 2022-05-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.FileField(blank=True, default=None, null=True, upload_to='books/', verbose_name='Ссылка на файл'),
        ),
    ]
