# Generated by Django 4.0.2 on 2022-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_book_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='index',
            field=models.IntegerField(default='1', unique=True),
        ),
    ]
