# Generated by Django 4.0.2 on 2022-05-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_book_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='index',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
