# Generated by Django 4.0.2 on 2022-05-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_book_index_book_id_book_ispublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='ico_url',
            field=models.ImageField(upload_to='ico/'),
        ),
    ]
