# Generated by Django 4.0.2 on 2022-05-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_python_ico_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoritm',
            name='isPublished',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='python',
            name='isPublished',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='test',
            name='isPublished',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
