# Generated by Django 4.0.2 on 2022-05-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_algoritm_ispublished_python_ispublished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='python',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.test'),
        ),
    ]
