# Generated by Django 4.0.2 on 2022-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_test_ispublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default=' ', verbose_name='Описание'),
        ),
    ]
